name: promart_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  bloc: ^8.1.1
  connectivity_repository:
    path: packages/connectivity_repository
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  form_inputs:
    path: packages/form_inputs
  geolocation_repository:
    path: packages/geolocation_repository
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.2
  intl: ^0.17.0
  url_launcher: ^6.1.7
  user_api:
    path: packages/user_api
  user_api_local:
    path: packages/user_api_local
  user_api_remote:
    path: packages/user_api_remote
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
